# vim: set et ts=2 ss=2 sw=2 :

title: "The stack frame"
author: "Emil Ohlsson"
email: emil@kottland.net
description: >
    Occasional rambling about stuff I might need to remember
baseurl: ""
url: "https://emilohlsson.github.io"
github_username:  EmilOhlsson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  
# Exclude these files from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
